# Generated by Django 3.0.4 on 2020-03-25 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_num_of_additions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuItemAdditionId', models.ManyToManyField(blank=True, related_name='orderItemAddition', to='orders.MenuItemAddition')),
                ('menuItemId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderItem', to='orders.MenuItem')),
            ],
        ),
    ]
