# Generated by Django 3.0.4 on 2020-03-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='desc',
            field=models.TextField(),
        ),
    ]
