# Generated by Django 3.0.4 on 2020-03-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='sort_id_asc',
            field=models.IntegerField(default=0),
        ),
    ]
