# Generated by Django 3.0.4 on 2020-03-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_menuitem_sort_id_asc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['sort_id_asc', '-size']},
        ),
        migrations.AddField(
            model_name='menuitemaddition',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
