# Generated by Django 3.0.4 on 2020-03-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200323_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='num_of_additions',
            field=models.IntegerField(default=0),
        ),
    ]
