# Generated by Django 3.0.4 on 2020-03-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grandTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
