# Generated by Django 3.0.4 on 2020-03-26 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_order_grandtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='grandTotal',
            new_name='grand_total',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='menuItemId',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='menuItemAdditionId',
            new_name='menu_item_addition',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='orderId',
        ),
        migrations.AddField(
            model_name='order',
            name='is_placed',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
